// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts,import_extension=.ts"
// @generated from file reusehub/listing/v1/listing.proto (package reusehub.listing.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateListingRequest, CreateListingResponse, GetListingRequest, GetListingResponse, SearchListingsRequest, SearchListingsResponse } from "./listing_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ListingService provides operations for managing listings
 *
 * @generated from service reusehub.listing.v1.ListingService
 */
export const ListingService = {
  typeName: "reusehub.listing.v1.ListingService",
  methods: {
    /**
     * GetListing retrieves a listing by ID
     *
     * @generated from rpc reusehub.listing.v1.ListingService.GetListing
     */
    getListing: {
      name: "GetListing",
      I: GetListingRequest,
      O: GetListingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CreateListing creates a new listing
     *
     * @generated from rpc reusehub.listing.v1.ListingService.CreateListing
     */
    createListing: {
      name: "CreateListing",
      I: CreateListingRequest,
      O: CreateListingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * SearchListings searches for listings with filters
     *
     * @generated from rpc reusehub.listing.v1.ListingService.SearchListings
     */
    searchListings: {
      name: "SearchListings",
      I: SearchListingsRequest,
      O: SearchListingsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

