// @generated by protoc-gen-es v2.4.0 with parameter "target=ts"
// @generated from file reusehub/listing/v1/listing.proto (package reusehub.listing.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file reusehub/listing/v1/listing.proto.
 */
export const file_reusehub_listing_v1_listing: GenFile = /*@__PURE__*/
  fileDesc("CiFyZXVzZWh1Yi9saXN0aW5nL3YxL2xpc3RpbmcucHJvdG8SE3JldXNlaHViLmxpc3RpbmcudjEikwEKB0xpc3RpbmcSCgoCaWQYASABKAkSDQoFdGl0bGUYAiABKAkSEwoLZGVzY3JpcHRpb24YAyABKAkSDQoFcHJpY2UYBCABKAESEAoIY2F0ZWdvcnkYBSABKAkSDwoHdXNlcl9pZBgGIAEoCRISCgpjcmVhdGVkX2F0GAcgASgDEhIKCnVwZGF0ZWRfYXQYCCABKAMiHwoRR2V0TGlzdGluZ1JlcXVlc3QSCgoCaWQYASABKAkiQwoSR2V0TGlzdGluZ1Jlc3BvbnNlEi0KB2xpc3RpbmcYASABKAsyHC5yZXVzZWh1Yi5saXN0aW5nLnYxLkxpc3RpbmcibAoUQ3JlYXRlTGlzdGluZ1JlcXVlc3QSDQoFdGl0bGUYASABKAkSEwoLZGVzY3JpcHRpb24YAiABKAkSDQoFcHJpY2UYAyABKAESEAoIY2F0ZWdvcnkYBCABKAkSDwoHdXNlcl9pZBgFIAEoCSJGChVDcmVhdGVMaXN0aW5nUmVzcG9uc2USLQoHbGlzdGluZxgBIAEoCzIcLnJldXNlaHViLmxpc3RpbmcudjEuTGlzdGluZyKFAQoVU2VhcmNoTGlzdGluZ3NSZXF1ZXN0Eg0KBXF1ZXJ5GAEgASgJEhAKCGNhdGVnb3J5GAIgASgJEhEKCW1pbl9wcmljZRgDIAEoARIRCgltYXhfcHJpY2UYBCABKAESEQoJcGFnZV9zaXplGAUgASgFEhIKCnBhZ2VfdG9rZW4YBiABKAkidQoWU2VhcmNoTGlzdGluZ3NSZXNwb25zZRIuCghsaXN0aW5ncxgBIAMoCzIcLnJldXNlaHViLmxpc3RpbmcudjEuTGlzdGluZxIXCg9uZXh0X3BhZ2VfdG9rZW4YAiABKAkSEgoKdG90YWxfc2l6ZRgDIAEoBTLIAgoOTGlzdGluZ1NlcnZpY2USXwoKR2V0TGlzdGluZxImLnJldXNlaHViLmxpc3RpbmcudjEuR2V0TGlzdGluZ1JlcXVlc3QaJy5yZXVzZWh1Yi5saXN0aW5nLnYxLkdldExpc3RpbmdSZXNwb25zZSIAEmgKDUNyZWF0ZUxpc3RpbmcSKS5yZXVzZWh1Yi5saXN0aW5nLnYxLkNyZWF0ZUxpc3RpbmdSZXF1ZXN0GioucmV1c2VodWIubGlzdGluZy52MS5DcmVhdGVMaXN0aW5nUmVzcG9uc2UiABJrCg5TZWFyY2hMaXN0aW5ncxIqLnJldXNlaHViLmxpc3RpbmcudjEuU2VhcmNoTGlzdGluZ3NSZXF1ZXN0GisucmV1c2VodWIubGlzdGluZy52MS5TZWFyY2hMaXN0aW5nc1Jlc3BvbnNlIgBCU1pRZ2l0aHViLmNvbS92bGFkaW1pclJhZG9qa292aWMvcmV1c2VodWItYXBpL2dlbnByb3RvL3JldXNlaHViL2xpc3RpbmcvdjE7bGlzdGluZ3YxYgZwcm90bzM");

/**
 * Listing represents a listing in the system
 *
 * @generated from message reusehub.listing.v1.Listing
 */
export type Listing = Message<"reusehub.listing.v1.Listing"> & {
  /**
   * Unique identifier for the listing
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Title of the listing
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * Description of the listing
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * Price of the listing
   *
   * @generated from field: double price = 4;
   */
  price: number;

  /**
   * Category of the listing
   *
   * @generated from field: string category = 5;
   */
  category: string;

  /**
   * ID of the user who created the listing
   *
   * @generated from field: string user_id = 6;
   */
  userId: string;

  /**
   * Timestamp when the listing was created
   *
   * @generated from field: int64 created_at = 7;
   */
  createdAt: bigint;

  /**
   * Timestamp when the listing was last updated
   *
   * @generated from field: int64 updated_at = 8;
   */
  updatedAt: bigint;
};

/**
 * Describes the message reusehub.listing.v1.Listing.
 * Use `create(ListingSchema)` to create a new message.
 */
export const ListingSchema: GenMessage<Listing> = /*@__PURE__*/
  messageDesc(file_reusehub_listing_v1_listing, 0);

/**
 * GetListingRequest is the request type for the GetListing RPC
 *
 * @generated from message reusehub.listing.v1.GetListingRequest
 */
export type GetListingRequest = Message<"reusehub.listing.v1.GetListingRequest"> & {
  /**
   * ID of the listing to retrieve
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message reusehub.listing.v1.GetListingRequest.
 * Use `create(GetListingRequestSchema)` to create a new message.
 */
export const GetListingRequestSchema: GenMessage<GetListingRequest> = /*@__PURE__*/
  messageDesc(file_reusehub_listing_v1_listing, 1);

/**
 * GetListingResponse is the response type for the GetListing RPC
 *
 * @generated from message reusehub.listing.v1.GetListingResponse
 */
export type GetListingResponse = Message<"reusehub.listing.v1.GetListingResponse"> & {
  /**
   * The requested listing information
   *
   * @generated from field: reusehub.listing.v1.Listing listing = 1;
   */
  listing?: Listing;
};

/**
 * Describes the message reusehub.listing.v1.GetListingResponse.
 * Use `create(GetListingResponseSchema)` to create a new message.
 */
export const GetListingResponseSchema: GenMessage<GetListingResponse> = /*@__PURE__*/
  messageDesc(file_reusehub_listing_v1_listing, 2);

/**
 * CreateListingRequest is the request type for the CreateListing RPC
 *
 * @generated from message reusehub.listing.v1.CreateListingRequest
 */
export type CreateListingRequest = Message<"reusehub.listing.v1.CreateListingRequest"> & {
  /**
   * Title for the new listing
   *
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * Description for the new listing
   *
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * Price for the new listing
   *
   * @generated from field: double price = 3;
   */
  price: number;

  /**
   * Category for the new listing
   *
   * @generated from field: string category = 4;
   */
  category: string;

  /**
   * ID of the user creating the listing
   *
   * @generated from field: string user_id = 5;
   */
  userId: string;
};

/**
 * Describes the message reusehub.listing.v1.CreateListingRequest.
 * Use `create(CreateListingRequestSchema)` to create a new message.
 */
export const CreateListingRequestSchema: GenMessage<CreateListingRequest> = /*@__PURE__*/
  messageDesc(file_reusehub_listing_v1_listing, 3);

/**
 * CreateListingResponse is the response type for the CreateListing RPC
 *
 * @generated from message reusehub.listing.v1.CreateListingResponse
 */
export type CreateListingResponse = Message<"reusehub.listing.v1.CreateListingResponse"> & {
  /**
   * The created listing information
   *
   * @generated from field: reusehub.listing.v1.Listing listing = 1;
   */
  listing?: Listing;
};

/**
 * Describes the message reusehub.listing.v1.CreateListingResponse.
 * Use `create(CreateListingResponseSchema)` to create a new message.
 */
export const CreateListingResponseSchema: GenMessage<CreateListingResponse> = /*@__PURE__*/
  messageDesc(file_reusehub_listing_v1_listing, 4);

/**
 * SearchListingsRequest is the request type for the SearchListings RPC
 *
 * @generated from message reusehub.listing.v1.SearchListingsRequest
 */
export type SearchListingsRequest = Message<"reusehub.listing.v1.SearchListingsRequest"> & {
  /**
   * Optional search query
   *
   * @generated from field: string query = 1;
   */
  query: string;

  /**
   * Optional category filter
   *
   * @generated from field: string category = 2;
   */
  category: string;

  /**
   * Optional minimum price filter
   *
   * @generated from field: double min_price = 3;
   */
  minPrice: number;

  /**
   * Optional maximum price filter
   *
   * @generated from field: double max_price = 4;
   */
  maxPrice: number;

  /**
   * Page size for pagination
   *
   * @generated from field: int32 page_size = 5;
   */
  pageSize: number;

  /**
   * Page token for pagination
   *
   * @generated from field: string page_token = 6;
   */
  pageToken: string;
};

/**
 * Describes the message reusehub.listing.v1.SearchListingsRequest.
 * Use `create(SearchListingsRequestSchema)` to create a new message.
 */
export const SearchListingsRequestSchema: GenMessage<SearchListingsRequest> = /*@__PURE__*/
  messageDesc(file_reusehub_listing_v1_listing, 5);

/**
 * SearchListingsResponse is the response type for the SearchListings RPC
 *
 * @generated from message reusehub.listing.v1.SearchListingsResponse
 */
export type SearchListingsResponse = Message<"reusehub.listing.v1.SearchListingsResponse"> & {
  /**
   * The listings matching the search criteria
   *
   * @generated from field: repeated reusehub.listing.v1.Listing listings = 1;
   */
  listings: Listing[];

  /**
   * Next page token for pagination
   *
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * Total number of listings matching the search criteria
   *
   * @generated from field: int32 total_size = 3;
   */
  totalSize: number;
};

/**
 * Describes the message reusehub.listing.v1.SearchListingsResponse.
 * Use `create(SearchListingsResponseSchema)` to create a new message.
 */
export const SearchListingsResponseSchema: GenMessage<SearchListingsResponse> = /*@__PURE__*/
  messageDesc(file_reusehub_listing_v1_listing, 6);

/**
 * ListingService provides operations for managing listings
 *
 * @generated from service reusehub.listing.v1.ListingService
 */
export const ListingService: GenService<{
  /**
   * GetListing retrieves a listing by ID
   *
   * @generated from rpc reusehub.listing.v1.ListingService.GetListing
   */
  getListing: {
    methodKind: "unary";
    input: typeof GetListingRequestSchema;
    output: typeof GetListingResponseSchema;
  },
  /**
   * CreateListing creates a new listing
   *
   * @generated from rpc reusehub.listing.v1.ListingService.CreateListing
   */
  createListing: {
    methodKind: "unary";
    input: typeof CreateListingRequestSchema;
    output: typeof CreateListingResponseSchema;
  },
  /**
   * SearchListings searches for listings with filters
   *
   * @generated from rpc reusehub.listing.v1.ListingService.SearchListings
   */
  searchListings: {
    methodKind: "unary";
    input: typeof SearchListingsRequestSchema;
    output: typeof SearchListingsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_reusehub_listing_v1_listing, 0);

