// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts,import_extension=none"
// @generated from file proto/reusehub/user/v1/user.proto (package reusehub.user.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateUserRequest, CreateUserResponse, GetUserRequest, GetUserResponse } from "./user_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * UserService provides operations for managing users
 *
 * @generated from service reusehub.user.v1.UserService
 */
export const UserService = {
  typeName: "reusehub.user.v1.UserService",
  methods: {
    /**
     * GetUser retrieves a user by ID
     *
     * @generated from rpc reusehub.user.v1.UserService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: GetUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CreateUser creates a new user
     *
     * @generated from rpc reusehub.user.v1.UserService.CreateUser
     */
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: CreateUserResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

