// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: reusehub/listing/v1/listing.proto

package listingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Listing represents a listing in the system
type Listing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the listing
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Title of the listing
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Description of the listing
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Price of the listing
	Price float64 `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	// Category of the listing
	Category string `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	// ID of the user who created the listing
	UserId string `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Timestamp when the listing was created
	CreatedAt int64 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp when the listing was last updated
	UpdatedAt     int64 `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing) Reset() {
	*x = Listing{}
	mi := &file_reusehub_listing_v1_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing) ProtoMessage() {}

func (x *Listing) ProtoReflect() protoreflect.Message {
	mi := &file_reusehub_listing_v1_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing.ProtoReflect.Descriptor instead.
func (*Listing) Descriptor() ([]byte, []int) {
	return file_reusehub_listing_v1_listing_proto_rawDescGZIP(), []int{0}
}

func (x *Listing) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Listing) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Listing) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Listing) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Listing) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Listing) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Listing) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Listing) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// GetListingRequest is the request type for the GetListing RPC
type GetListingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the listing to retrieve
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingRequest) Reset() {
	*x = GetListingRequest{}
	mi := &file_reusehub_listing_v1_listing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingRequest) ProtoMessage() {}

func (x *GetListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reusehub_listing_v1_listing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingRequest.ProtoReflect.Descriptor instead.
func (*GetListingRequest) Descriptor() ([]byte, []int) {
	return file_reusehub_listing_v1_listing_proto_rawDescGZIP(), []int{1}
}

func (x *GetListingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetListingResponse is the response type for the GetListing RPC
type GetListingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested listing information
	Listing       *Listing `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingResponse) Reset() {
	*x = GetListingResponse{}
	mi := &file_reusehub_listing_v1_listing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingResponse) ProtoMessage() {}

func (x *GetListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reusehub_listing_v1_listing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingResponse.ProtoReflect.Descriptor instead.
func (*GetListingResponse) Descriptor() ([]byte, []int) {
	return file_reusehub_listing_v1_listing_proto_rawDescGZIP(), []int{2}
}

func (x *GetListingResponse) GetListing() *Listing {
	if x != nil {
		return x.Listing
	}
	return nil
}

// CreateListingRequest is the request type for the CreateListing RPC
type CreateListingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Title for the new listing
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Description for the new listing
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Price for the new listing
	Price float64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	// Category for the new listing
	Category string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	// ID of the user creating the listing
	UserId        string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListingRequest) Reset() {
	*x = CreateListingRequest{}
	mi := &file_reusehub_listing_v1_listing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingRequest) ProtoMessage() {}

func (x *CreateListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reusehub_listing_v1_listing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingRequest.ProtoReflect.Descriptor instead.
func (*CreateListingRequest) Descriptor() ([]byte, []int) {
	return file_reusehub_listing_v1_listing_proto_rawDescGZIP(), []int{3}
}

func (x *CreateListingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateListingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateListingRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateListingRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateListingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// CreateListingResponse is the response type for the CreateListing RPC
type CreateListingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created listing information
	Listing       *Listing `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListingResponse) Reset() {
	*x = CreateListingResponse{}
	mi := &file_reusehub_listing_v1_listing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingResponse) ProtoMessage() {}

func (x *CreateListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reusehub_listing_v1_listing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingResponse.ProtoReflect.Descriptor instead.
func (*CreateListingResponse) Descriptor() ([]byte, []int) {
	return file_reusehub_listing_v1_listing_proto_rawDescGZIP(), []int{4}
}

func (x *CreateListingResponse) GetListing() *Listing {
	if x != nil {
		return x.Listing
	}
	return nil
}

// SearchListingsRequest is the request type for the SearchListings RPC
type SearchListingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional search query
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Optional category filter
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	// Optional minimum price filter
	MinPrice float64 `protobuf:"fixed64,3,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	// Optional maximum price filter
	MaxPrice float64 `protobuf:"fixed64,4,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	// Page size for pagination
	PageSize int32 `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page token for pagination
	PageToken     string `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchListingsRequest) Reset() {
	*x = SearchListingsRequest{}
	mi := &file_reusehub_listing_v1_listing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchListingsRequest) ProtoMessage() {}

func (x *SearchListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reusehub_listing_v1_listing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchListingsRequest.ProtoReflect.Descriptor instead.
func (*SearchListingsRequest) Descriptor() ([]byte, []int) {
	return file_reusehub_listing_v1_listing_proto_rawDescGZIP(), []int{5}
}

func (x *SearchListingsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchListingsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SearchListingsRequest) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *SearchListingsRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *SearchListingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchListingsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// SearchListingsResponse is the response type for the SearchListings RPC
type SearchListingsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The listings matching the search criteria
	Listings []*Listing `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	// Next page token for pagination
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total number of listings matching the search criteria
	TotalSize     int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchListingsResponse) Reset() {
	*x = SearchListingsResponse{}
	mi := &file_reusehub_listing_v1_listing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchListingsResponse) ProtoMessage() {}

func (x *SearchListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reusehub_listing_v1_listing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchListingsResponse.ProtoReflect.Descriptor instead.
func (*SearchListingsResponse) Descriptor() ([]byte, []int) {
	return file_reusehub_listing_v1_listing_proto_rawDescGZIP(), []int{6}
}

func (x *SearchListingsResponse) GetListings() []*Listing {
	if x != nil {
		return x.Listings
	}
	return nil
}

func (x *SearchListingsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *SearchListingsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

var File_reusehub_listing_v1_listing_proto protoreflect.FileDescriptor

const file_reusehub_listing_v1_listing_proto_rawDesc = "" +
	"\n" +
	"!reusehub/listing/v1/listing.proto\x12\x13reusehub.listing.v1\"\xda\x01\n" +
	"\aListing\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"#\n" +
	"\x11GetListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x12GetListingResponse\x126\n" +
	"\alisting\x18\x01 \x01(\v2\x1c.reusehub.listing.v1.ListingR\alisting\"\x99\x01\n" +
	"\x14CreateListingRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\"O\n" +
	"\x15CreateListingResponse\x126\n" +
	"\alisting\x18\x01 \x01(\v2\x1c.reusehub.listing.v1.ListingR\alisting\"\xbf\x01\n" +
	"\x15SearchListingsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1b\n" +
	"\tmin_price\x18\x03 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x04 \x01(\x01R\bmaxPrice\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"\x99\x01\n" +
	"\x16SearchListingsResponse\x128\n" +
	"\blistings\x18\x01 \x03(\v2\x1c.reusehub.listing.v1.ListingR\blistings\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize2\xc8\x02\n" +
	"\x0eListingService\x12_\n" +
	"\n" +
	"GetListing\x12&.reusehub.listing.v1.GetListingRequest\x1a'.reusehub.listing.v1.GetListingResponse\"\x00\x12h\n" +
	"\rCreateListing\x12).reusehub.listing.v1.CreateListingRequest\x1a*.reusehub.listing.v1.CreateListingResponse\"\x00\x12k\n" +
	"\x0eSearchListings\x12*.reusehub.listing.v1.SearchListingsRequest\x1a+.reusehub.listing.v1.SearchListingsResponse\"\x00BSZQgithub.com/vladimirRadojkovic/reusehub-api/genproto/reusehub/listing/v1;listingv1b\x06proto3"

var (
	file_reusehub_listing_v1_listing_proto_rawDescOnce sync.Once
	file_reusehub_listing_v1_listing_proto_rawDescData []byte
)

func file_reusehub_listing_v1_listing_proto_rawDescGZIP() []byte {
	file_reusehub_listing_v1_listing_proto_rawDescOnce.Do(func() {
		file_reusehub_listing_v1_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reusehub_listing_v1_listing_proto_rawDesc), len(file_reusehub_listing_v1_listing_proto_rawDesc)))
	})
	return file_reusehub_listing_v1_listing_proto_rawDescData
}

var file_reusehub_listing_v1_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_reusehub_listing_v1_listing_proto_goTypes = []any{
	(*Listing)(nil),                // 0: reusehub.listing.v1.Listing
	(*GetListingRequest)(nil),      // 1: reusehub.listing.v1.GetListingRequest
	(*GetListingResponse)(nil),     // 2: reusehub.listing.v1.GetListingResponse
	(*CreateListingRequest)(nil),   // 3: reusehub.listing.v1.CreateListingRequest
	(*CreateListingResponse)(nil),  // 4: reusehub.listing.v1.CreateListingResponse
	(*SearchListingsRequest)(nil),  // 5: reusehub.listing.v1.SearchListingsRequest
	(*SearchListingsResponse)(nil), // 6: reusehub.listing.v1.SearchListingsResponse
}
var file_reusehub_listing_v1_listing_proto_depIdxs = []int32{
	0, // 0: reusehub.listing.v1.GetListingResponse.listing:type_name -> reusehub.listing.v1.Listing
	0, // 1: reusehub.listing.v1.CreateListingResponse.listing:type_name -> reusehub.listing.v1.Listing
	0, // 2: reusehub.listing.v1.SearchListingsResponse.listings:type_name -> reusehub.listing.v1.Listing
	1, // 3: reusehub.listing.v1.ListingService.GetListing:input_type -> reusehub.listing.v1.GetListingRequest
	3, // 4: reusehub.listing.v1.ListingService.CreateListing:input_type -> reusehub.listing.v1.CreateListingRequest
	5, // 5: reusehub.listing.v1.ListingService.SearchListings:input_type -> reusehub.listing.v1.SearchListingsRequest
	2, // 6: reusehub.listing.v1.ListingService.GetListing:output_type -> reusehub.listing.v1.GetListingResponse
	4, // 7: reusehub.listing.v1.ListingService.CreateListing:output_type -> reusehub.listing.v1.CreateListingResponse
	6, // 8: reusehub.listing.v1.ListingService.SearchListings:output_type -> reusehub.listing.v1.SearchListingsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_reusehub_listing_v1_listing_proto_init() }
func file_reusehub_listing_v1_listing_proto_init() {
	if File_reusehub_listing_v1_listing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reusehub_listing_v1_listing_proto_rawDesc), len(file_reusehub_listing_v1_listing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reusehub_listing_v1_listing_proto_goTypes,
		DependencyIndexes: file_reusehub_listing_v1_listing_proto_depIdxs,
		MessageInfos:      file_reusehub_listing_v1_listing_proto_msgTypes,
	}.Build()
	File_reusehub_listing_v1_listing_proto = out.File
	file_reusehub_listing_v1_listing_proto_goTypes = nil
	file_reusehub_listing_v1_listing_proto_depIdxs = nil
}
